--YEAR: 0000

SELECT COUNT(*),STATE_CODE,P,(COUNT(*)/P)*1000 AS ACCIDENT_PER_THOUSAND_POP
from 
SIYUCHEN.ACCIDENT NATURAL JOIN SIYUCHEN.LOCATION NATURAL JOIN 
    
    (SELECT POPULATION_COUNT AS P,STATE_CODE
     FROM SIYUCHEN.POPULATION
     WHERE YEAR = 0000
    )
GROUP BY STATE_CODE,P
ORDER BY  ACCIDENT_PER_THOUSAND_POP DESC