-- LATITUDE1: 00
-- LATITUDE2: 01

SELECT COUNT(*) AS ACCIDENT_COUNT,TO_CHAR(START_TIME, 'MM') AS MONTH FROM SIYUCHEN.ACCIDENT 
           WHERE (LATITUDE>=00 AND LATITUDE < 01)  
GROUP BY TO_CHAR(START_TIME, 'MM')
ORDER BY TO_CHAR(START_TIME, 'MM') ASC