SELECT COUNT(*),TO_CHAR(START_TIME, 'MM') AS MONTH  FROM SIYUCHEN.ACCIDENT 
           WHERE (LATITUDE>=25 AND LATITUDE <30)  
GROUP BY TO_CHAR(START_TIME, 'MM')
ORDER BY TO_CHAR(START_TIME, 'MM') ASC

SELECT COUNT(*),TO_CHAR(START_TIME, 'MM') AS MONTH  FROM SIYUCHEN.ACCIDENT 
           WHERE (LATITUDE>=30 AND LATITUDE <35)  
GROUP BY TO_CHAR(START_TIME, 'MM')
ORDER BY TO_CHAR(START_TIME, 'MM') ASC

SELECT COUNT(*),TO_CHAR(START_TIME, 'MM') AS MONTH  FROM SIYUCHEN.ACCIDENT 
           WHERE (LATITUDE>=35 AND LATITUDE <40)  
GROUP BY TO_CHAR(START_TIME, 'MM')
ORDER BY TO_CHAR(START_TIME, 'MM') ASC

SELECT COUNT(*),TO_CHAR(START_TIME, 'MM') AS MONTH  FROM SIYUCHEN.ACCIDENT 
           WHERE (LATITUDE>=40 AND LATITUDE <45)  
GROUP BY TO_CHAR(START_TIME, 'MM')
ORDER BY TO_CHAR(START_TIME, 'MM') ASC

SELECT COUNT(*),TO_CHAR(START_TIME, 'MM') AS MONTH  FROM SIYUCHEN.ACCIDENT 
           WHERE (LATITUDE>=45 AND LATITUDE <50)  
GROUP BY TO_CHAR(START_TIME, 'MM')
ORDER BY TO_CHAR(START_TIME, 'MM') ASC